documentation 📝:
- any: ['docs/**/*.md', 'community/**/*.md']
  all: ['!i18n/**/*.md']
dependencies 📦:
  - 'yarn.lock'
  - 'package.json'
enhancement ✨:
  - 'tsconfig.json'
  - '.prettierrc'
  - '.prettierignore'
  - '.markdownlint.json'
maintenance 📈:
  - '.github/CODEOWNERS'
  - '.github/*.md'
  - '.github/*.yml'
  - '.github/*.json'
  - '.vscode'
  - 'docusaurus.config.js'
i18n 🌐:
  - 'i18n/**'
annex 💠:
  - 'docs/ecosystem/annexes/*.md'
  - 'i18n/**/docusaurus-plugin-content-docs/current/ecosystem/annexes/*.md'
package 📦:
  - 'docs/ecosystem/packages*.md'
  - 'i18n/**/docusaurus-plugin-content-docs/current/ecosystem/packages/*.md'
plugin 🧿:
  - 'docs/ecosystem/plugins/*.md'
  - 'i18n/**/docusaurus-plugin-content-docs/current/ecosystem/plugins/*.md'
ci 🤖:
  - '.github/workflows/*.yml'
  - '.all-contributorsrc'
  - 'crowdin.yml'
