nodeLinker: node-modules

packageExtensions:
  '@docsearch/react@*':
    peerDependencies:
      '@algolia/client-search': '*'
  '@docusaurus/core@*':
    dependencies:
      typescript: '*'
  '@docusaurus/mdx-loader@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/plugin-content-blog@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/plugin-content-docs@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/plugin-content-pages@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/plugin-debug@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@docusaurus/plugin-google-analytics@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@docusaurus/plugin-google-gtag@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@docusaurus/plugin-ideal-image@*':
    peerDependencies:
      '@babel/core': '*'
      prop-types: '*'
      react-dev-utils: '*'
  '@docusaurus/plugin-pwa@*':
    peerDependencies:
      prism-react-renderer: '*'
  '@docusaurus/plugin-sitemap@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@docusaurus/preset-classic@*':
    peerDependencies:
      '@algolia/client-search': '*'
      '@babel/core': '*'
      prism-react-renderer: '*'
      webpack: '*'
  '@docusaurus/theme-classic@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@docusaurus/theme-common@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@docusaurus/theme-live-codeblock@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@docusaurus/theme-search-algolia@*':
    peerDependencies:
      '@algolia/client-search': '*'
      '@babel/core': '*'
      prism-react-renderer: '*'
      webpack: '*'
  '@docusaurus/utils-validation@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  'react-dev-utils@*':
    peerDependencies:
      '@babel/core': '*'
      typescript: '*'
      webpack: '*'
  'zw@*':
    peerDependencies:
      '@algolia/client-search': '*'
      '@babel/core': '*'
      prop-types: '*'
      react: '*'
      react-dev-utils: '*'
      react-dom: '*'
      webpack: '*'

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.2.0.cjs
