nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  '@docusaurus/core@*':
    dependencies:
      'react': '*'
      'typescript': '*'
  'zw@*':
    peerDependencies:
      '@babel/core': '*'
      'react-dev-utils@*': '*'
      '@algolia/client-search': '*'
      'prop-types': '*'
      'react': '*'
      'react-dom': '*'
      'webpack': '*'
  '@docusaurus/mdx-loader@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/plugin-content-blog@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/plugin-content-docs@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/plugin-content-pages@*':
    peerDependencies:
      '@babel/core': '*'
  '@docusaurus/preset-classic@*':
    peerDependencies:
      '@algolia/client-search': '*'
      'prism-react-renderer': '*'
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/theme-live-codeblock@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/plugin-debug@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/plugin-sitemap@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/plugin-pwa@*':
    peerDependencies:
      'prism-react-renderer': '*'
  '@docusaurus/theme-classic@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/theme-common@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/theme-search-algolia@*':
    peerDependencies:
      '@algolia/client-search': '*'
      'prism-react-renderer': '*'
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/plugin-ideal-image@*':
    peerDependencies:
      '@babel/core': '*'
      'prop-types': '*'
      'react-dev-utils@*': '*'
  '@docsearch/react@*':
    peerDependencies:
      '@algolia/client-search': '*'
  '@docusaurus/utils-validation@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  'react-dev-utils@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
      'typescript': '*'
  '@docusaurus/plugin-google-analytics@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@docusaurus/plugin-google-gtag@*':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
