nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "react@*":
    dependencies:
      prop-types: "*"

packageExtensions:
  "@babel/plugin-something@*":
    peerDependencies:
      "@babel/core": "*"
