nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "react@*":
    dependencies:
      prop-types: "*"
  "@docusaurus/plugin-content-blog@*":
  "@docusaurus/plugin-content-docs@*":
  "@docusaurus/plugin-content-pages@*":
  "@docusaurus/theme-classic@*":
    peerDependencies:
      "@babel/core": "*"
