project_id_env: PROJECT_ID
api_token_env: ZI_CROWDIN_TOKEN
base_url: 'https://digitalclouds.crowdin.com'
base_path: .
commit_message: '[ci skip]'
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*.json
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
  - source: /community/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
