name = "zw"
type = "webpack"
route = ''
zone_id = '7600c132f040aea60b0533ad801986d5'
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-16"
kv_namespaces = [
         { binding = "ZW", id = "46d20cee9bea4b27909881857da7f21b" }
]
