---
name: '🌐 Crowdin'

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#    paths:
#      - 'docs/**'
jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: '⤵️ Check out code from GitHub'
      uses: actions/checkout@v2
    - name: '🚀 Run Crowdin action'
      uses: crowdin/github-action@1.4.7
      with:
        upload_sources: false
        upload_translations: false
        download_translations: true
        push_translations: true
        create_pull_request: true
        #pull_request_labels: 'enhancement ✨'
      env:
        GITHUB_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
